
[servers]

  # 您可以依照您的意愿缩进.使用空格或Tab.TOML不会在意.
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[api]
router = "router"
port = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true
  [api.main]
  address=":51001"

[cron]
  [cron.main]
  [cron.tesk]
  task=[]